name: Deploy to Portainer

on:
    push:
        branches:
            - main # หรือ branch ที่คุณต้องการให้ Deploy

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            # ขั้นตอนเสริม: หากต้อง Build Docker Image ก่อน
            # - name: Build and Push Docker Image
            #   run: |
            #     docker build -t your-registry/image:latest .
            #     docker push your-registry/image:latest

            - name: Trigger Portainer Webhook
              run: |
                  curl -k -X POST "${{ secrets.PORTAINER_WEBHOOK_URL_DEV }}"
